version: '3.8'
services:
  typesense:
    image: typesense/typesense:0.26.0.rc55
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=l2bb7LrLzo0JCqYVGr5hhbknGEYJk0dYsqexICLZsPkMPOTp --enable-cors'
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: qwer1236
      POSTGRES_USER: nextappadmin
      POSTGRES_DB: nextapp