export const summerImage = {
	'summer-earrings1': 'summer-earrings1.jpg',
	'summer-sneakers1': 'summer-sneakers1.jpg',
	'summer-sunglasses3': 'summer-sunglasses3.jpg',
	'summer-earrings2': 'summer-earrings2.jpg',
	'summer-sneakers2': 'summer-sneakers2.jpg',
	'summer-sunglasses4': 'summer-sunglasses4.jpg',
	'summer-hoodie1': 'summer-hoodie1.jpg',
	'summer-sneakers3': 'summer-sneakers3.jpg',
	'summer-t-shirt10': 'summer-t-shirt10.jpg',
	'summer-hoodie2': 'summer-hoodie2.jpg',
	'summer-sneakers4': 'summer-sneakers4.jpg',
	'summer-t-shirt1': 'summer-t-shirt1.jpg',
	'summer-hoodie3': 'summer-hoodie3.jpg',
	'summer-sport-pants1': 'summer-sport-pants1.jpg',
	'summer-t-shirt2': 'summer-t-shirt2.jpg',
	'summer-hoodie4': 'summer-hoodie4.jpg',
	'summer-sport-pants2': 'summer-sport-pants2.jpg',
	'summer-t-shirt3': 'summer-t-shirt3.jpg',
	'summer-hoodie5': 'summer-hoodie5.jpg',
	'summer-sport-pants3': 'summer-sport-pants3.jpg',
	'summer-t-shirt4': 'summer-t-shirt4.jpg',
	'summer-hoodie6': 'summer-hoodie6.jpg',
	'summer-sport-pants4': 'summer-sport-pants4.jpg',
	'summer-t-shirt5': 'summer-t-shirt5.jpg',
	'summer-shorts-sm1': 'summer-shorts-sm1.jpg',
	'summer-straw-hat1': 'summer-straw-hat1.jpg',
	'summer-t-shirt6': 'summer-t-shirt6.jpg',
	'summer-shorts-sm2': 'summer-shorts-sm2.jpg',
	'summer-straw-hat2': 'summer-straw-hat2.jpg',
	'summer-t-shirt7': 'summer-t-shirt7.jpg',
	'summer-shorts-sm3': 'summer-shorts-sm3.jpg',
	'summer-sunglasses1': 'summer-sunglasses1.jpg',
	'summer-t-shirt8': 'summer-t-shirt8.jpg',
	'summer-shorts-sm4': 'summer-shorts-sm4.jpg',
	'summer-sunglasses2': 'summer-sunglasses2.jpg',
	'summer-t-shirt9': 'summer-t-shirt9.jpg',
	'summer-collection': 'summer-collection.jpg'
};

export const winterImage = {
	'winter-boots-women1': 'winter-boots-women1.jpg',
	'winter-leather-elegant-boots1':
		'winter-leather-elegant-boots1.jpg',
	'winter-boots-women2': 'winter-boots-women2.jpg',
	'winter-leather-elegant-boots2':
		'winter-leather-elegant-boots2.jpg',
	'winter-earmuffs1': 'winter-earmuffs1.jpg',
	'winter-leather-elegant-boots3':
		'winter-leather-elegant-boots3.jpg',
	'winter-earmuffs2': 'winter-earmuffs2.jpg',
	'winter-leather-elegant-boots4':
		'winter-leather-elegant-boots4.jpg',
	'winter-gloves1': 'winter-gloves1.jpg',
	'winter-pants-jeans1': 'winter-pants-jeans1.jpg',
	'winter-gloves2': 'winter-gloves2.jpg',
	'winter-pants-sport1': 'winter-pants-sport1.jpg',
	'winter-gloves3': 'winter-gloves3.jpg',
	'winter-pants-sport2': 'winter-pants-sport2.jpg',
	'winter-gloves4': 'winter-gloves4.jpg',
	'winter-t-shirt1': 'winter-t-shirt1.jpg',
	'winter-hoodie1': 'winter-hoodie1.jpg',
	'winter-t-shirt2': 'winter-t-shirt2.jpg',
	'winter-hoodie2': 'winter-hoodie2.jpg',
	'winter-t-shirt3': 'winter-t-shirt3.jpg',
	'winter-hoodie3': 'winter-hoodie3.jpg',
	'winter-t-shirt4': 'winter-t-shirt4.jpg',
	'winter-hoodie4': 'winter-hoodie4.jpg',
	'winter-t-shirt5': 'winter-t-shirt5.jpg',
	'winter-hoodie5': 'winter-hoodie5.jpg',
	'winter-t-shirt6': 'winter-t-shirt6.jpg',
	'winter-hoodie6': 'winter-hoodie6.jpg',
	'winter-trekking-boots1': 'winter-trekking-boots1.jpg',
	'winter-trekking-boots2': 'winter-trekking-boots2.jpg',
	'winter-trekking-boots3': 'winter-trekking-boots3.jpg',
	'winter-trekking-boots4': 'winter-trekking-boots4.jpg',
	'winter-collection': 'winter-collection.jpg'
};
